/**
 * Canonical origin.
 *
 * Order matters. `NEXT_PUBLIC_SITE_URL` wins if set. On Vercel, production is
 * the apex and previews advertise their own deployment URL rather than the
 * production domain. Outside Vercel we are running locally, so this resolves
 * to localhost — otherwise a magic link generated by `npm run dev` would send
 * you to the live site, and the session cookie would land on the wrong origin.
 */
function resolveSiteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) return process.env.NEXT_PUBLIC_SITE_URL;
  if (process.env.VERCEL_ENV === "production") return "https://icetrack.vip";
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  if (process.env.NODE_ENV === "development") {
    return `http://localhost:${process.env.PORT ?? 3000}`;
  }
  return "https://icetrack.vip";
}

export const SITE_URL = resolveSiteUrl();

export const SITE_NAME = "IceTrack";
