-- One-off: attach freely licensed photographs from Wikimedia Commons.
--
-- These are pictures of the model, not of the individual item owned: a
-- photograph of a specific person's aircraft or car almost never exists under
-- a free licence, while the type is well covered. Every row therefore sets
-- image_is_representative.
--
-- Only CC0, public domain, CC BY and CC BY-SA files are used, and each carries
-- its author, licence and source page. Press and agency photographs are not
-- usable here whatever credit is given: attribution is an obligation that
-- comes with a free licence, not a substitute for one.

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0749%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0749%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0749%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0749%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Gulfstream_G650ER,_EBACE_2018,_Le_Grand-Saconnex_(BL7C0749).jpg"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-gulfstream-g650';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg/1920px-Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg/1920px-Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Bugatti_Chiron,_GIMS_2018,_Le_Grand-Saconnex_(1X7A1765).jpg"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-bugatti-chiron';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg/1920px-Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg/1920px-Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_%281%29%2C_5._April_2012%2C_D%C3%BCsseldorf.jpg","author":"M 93","license":"CC BY-SA 3.0 de","sourcePage":"https://commons.wikimedia.org/wiki/File:Bugatti_Veyron_16.4_%E2%80%93_Frontansicht_(1),_5._April_2012,_D%C3%BCsseldorf.jpg"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-bugatti-veyron';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Bugatti_Centodieci_side.png/1920px-Bugatti_Centodieci_side.png', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Bugatti_Centodieci_side.png/1920px-Bugatti_Centodieci_side.png","author":"pelican-actor","license":"CC BY 2.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Bugatti_Centodieci_side.png"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-bugatti-centodieci';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Mercedes-AMG_Project_One%2C_Frankfurt_%281Y7A3446%29.jpg/1920px-Mercedes-AMG_Project_One%2C_Frankfurt_%281Y7A3446%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Mercedes-AMG_Project_One%2C_Frankfurt_%281Y7A3446%29.jpg/1920px-Mercedes-AMG_Project_One%2C_Frankfurt_%281Y7A3446%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Mercedes-AMG_Project_One,_Frankfurt_(1Y7A3446).jpg"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-mercedes-amg-one';

update assets set image_url = 'https://upload.wikimedia.org/wikipedia/commons/6/63/Bombardier_Global_Express_1294133.jpg', image_credit = '{"url":"https://upload.wikimedia.org/wikipedia/commons/6/63/Bombardier_Global_Express_1294133.jpg","author":"Richard Smith","license":"CC BY-SA 2.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Bombardier_Global_Express_1294133.jpg"}'::jsonb, image_is_representative = true where slug = 'cristiano-ronaldo-global-express';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg/1920px-Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg/1920px-Bugatti_Chiron%2C_GIMS_2018%2C_Le_Grand-Saconnex_%281X7A1765%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Bugatti_Chiron,_GIMS_2018,_Le_Grand-Saconnex_(1X7A1765).jpg"}'::jsonb, image_is_representative = true where slug = 'canelo-alvarez-bugatti-chiron';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Gulfstream_G650ER,_EBACE_2018,_Le_Grand-Saconnex_(BL7C0752).jpg"}'::jsonb, image_is_representative = true where slug = 'michael-jordan-gulfstream-g650er';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Gulfstream_G550%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0727%29.jpg/1920px-Gulfstream_G550%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0727%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Gulfstream_G550%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0727%29.jpg/1920px-Gulfstream_G550%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0727%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Gulfstream_G550,_EBACE_2018,_Le_Grand-Saconnex_(BL7C0727).jpg"}'::jsonb, image_is_representative = true where slug = 'michael-jordan-gulfstream-g550';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg/1920px-Gulfstream_G650ER%2C_EBACE_2018%2C_Le_Grand-Saconnex_%28BL7C0752%29.jpg","author":"Matti Blume","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Gulfstream_G650ER,_EBACE_2018,_Le_Grand-Saconnex_(BL7C0752).jpg"}'::jsonb, image_is_representative = true where slug = 'elon-musk-gulfstream-g650er';

update assets set image_url = 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Serene.jpg', image_credit = '{"url":"https://upload.wikimedia.org/wikipedia/commons/d/dc/Serene.jpg","author":"Liberty123de","license":"CC BY-SA 3.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Serene.jpg"}'::jsonb, image_is_representative = true where slug = 'mohammed-bin-salman-serene';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Topaz_13.jpg/1920px-Topaz_13.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Topaz_13.jpg/1920px-Topaz_13.jpg","author":"Géry Parent","license":"Public domain","sourcePage":"https://commons.wikimedia.org/wiki/File:Topaz_13.jpg"}'::jsonb, image_is_representative = true where slug = 'sheikh-mansour-a-plus';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Pagani_Huayra_-_Flickr_-_andrewbasterfield.jpg/1920px-Pagani_Huayra_-_Flickr_-_andrewbasterfield.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Pagani_Huayra_-_Flickr_-_andrewbasterfield.jpg/1920px-Pagani_Huayra_-_Flickr_-_andrewbasterfield.jpg","author":"Andrew Basterfield","license":"CC BY-SA 2.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Pagani_Huayra_-_Flickr_-_andrewbasterfield.jpg"}'::jsonb, image_is_representative = true where slug = 'dwayne-johnson-pagani-huayra';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/LaFerrari_in_Beverly_Hills_%2814563979888%29.jpg/1920px-LaFerrari_in_Beverly_Hills_%2814563979888%29.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/LaFerrari_in_Beverly_Hills_%2814563979888%29.jpg/1920px-LaFerrari_in_Beverly_Hills_%2814563979888%29.jpg","author":"Axion23","license":"CC BY 2.0","sourcePage":"https://commons.wikimedia.org/wiki/File:LaFerrari_in_Beverly_Hills_(14563979888).jpg"}'::jsonb, image_is_representative = true where slug = 'dwayne-johnson-laferrari';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Gulfstream_G-400.jpg/1920px-Gulfstream_G-400.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Gulfstream_G-400.jpg/1920px-Gulfstream_G-400.jpg","author":"Planephotoman","license":"CC BY 2.0","sourcePage":"https://commons.wikimedia.org/wiki/File:Gulfstream_G-400.jpg"}'::jsonb, image_is_representative = true where slug = 'tom-cruise-gulfstream-iv';

update assets set image_url = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/XOJET_Bombardier_Challenger_300_N538XJ_approaching_Newark_Airport.jpg/1920px-XOJET_Bombardier_Challenger_300_N538XJ_approaching_Newark_Airport.jpg', image_credit = '{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/XOJET_Bombardier_Challenger_300_N538XJ_approaching_Newark_Airport.jpg/1920px-XOJET_Bombardier_Challenger_300_N538XJ_approaching_Newark_Airport.jpg","author":"Adam Moreira (AEMoreira042281)","license":"CC BY-SA 4.0","sourcePage":"https://commons.wikimedia.org/wiki/File:XOJET_Bombardier_Challenger_300_N538XJ_approaching_Newark_Airport.jpg"}'::jsonb, image_is_representative = true where slug = 'tom-cruise-challenger-300';
